### PR TITLE
fixed inability to read environmental variables

### PR DESCRIPTION
**Pull request by ossydotpy**
As the title suggests, for some reason, after creating a .env file and setting the variables correctly, there were still problems trying to gettheir values.

so, I propose a fix. 
Using `os.getenv("PROJECT_ID")` to read the variables.
This worked for me but the already implemented env["PROJECT_ID"] didn't.

Thanks.

### CODE REVIEW

**Comment by theeldermillenial** [comment]
Thanks for the PR. Before accepting this, can you give me some details about your issue?

Did you save your environment file as `.env`?

What is the error message you received?

**Comment by ossydotpy** [comment]
Thanks for answering.

To answer your question Yes, I have saved the variables in a `.env` file.

I have done this both locally and through relpit.
There's the same error message each time.

```  File "/home/runner/bot/venv/lib/python3.10/site-packages/minswap/pools.py", line 386, in get_pool_by_id
    api = blockfrost.BlockFrostApi(env["PROJECT_ID"])
KeyError: 'PROJECT_ID'```

**Comment by theeldermillenial** [comment]
Excellent. Can you give me the full stack trace? I need to see exactly what the error is.

Also, can you let me know what version of Python you're using?

I want to see if I can reproduce the error.

**Comment by ossydotpy** [comment]
I'm using python 3.10.7


Traceback (most recent call last):
  File "get_prices.py", line 18, in <module>
    print(f"{datetime.now()}: {pool} -> {pools.get_pool_by_id(pool_id).price}")
  File "/home/runner/bot/venv/lib/python3.10/site-packages/minswap/pools.py", line 386, in get_pool_by_id
    api = blockfrost.BlockFrostApi(env["PROJECT_ID"])
KeyError: 'PROJECT_ID'


This is the trace from running [get_prices.py](https://github.com/theeldermillenial/minswap-py/blob/master/examples/get_prices.py) without any modifications.

**Pull request closed without merging**
